//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR15
{
    using System;
    using System.Collections.Generic;
    
    public partial class boardformfactorcase
    {
        public int id { get; set; }
        public int caseid { get; set; }
        public int formfactorid { get; set; }
    
        public virtual @case @case { get; set; }
        public virtual formfactor formfactor { get; set; }
    }
}
