//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR15
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpu
    {
        public int id { get; set; }
        public int socketid { get; set; }
        public int numberofcores { get; set; }
        public double basecorefrequency { get; set; }
        public double maxcorefrequency { get; set; }
        public int cachel3 { get; set; }
        public Nullable<int> igpuid { get; set; }
        public int thermalpower { get; set; }
        public bool hasigpu { get; set; }
    
        public virtual basepart basepart { get; set; }
        public virtual igpu igpu { get; set; }
        public virtual socket socket { get; set; }
    }
}
