//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR15
{
    using System;
    using System.Collections.Generic;
    
    public partial class motherboard
    {
        public int id { get; set; }
        public int socketid { get; set; }
        public int formfactorid { get; set; }
        public int memoryslots { get; set; }
        public int memorytypeid { get; set; }
        public int pcislots { get; set; }
        public int sataports { get; set; }
        public int usbports { get; set; }
    
        public virtual basepart basepart { get; set; }
        public virtual formfactor formfactor { get; set; }
        public virtual memorytype memorytype { get; set; }
        public virtual socket socket { get; set; }
    }
}
