//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR15
{
    using System;
    using System.Collections.Generic;
    
    public partial class partassembly
    {
        public int id { get; set; }
        public int partid { get; set; }
        public int assemblyid { get; set; }
    
        public virtual assembly assembly { get; set; }
        public virtual basepart basepart { get; set; }
    }
}
