//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR15
{
    using System;
    using System.Collections.Generic;
    
    public partial class powersupply
    {
        public int id { get; set; }
        public int power { get; set; }
        public int fandimensionid { get; set; }
        public int certificationid { get; set; }
    
        public virtual basepart basepart { get; set; }
        public virtual certificate certificate { get; set; }
        public virtual fandimension fandimension { get; set; }
    }
}
