//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR15
{
    using System;
    using System.Collections.Generic;
    
    public partial class socketprocessorcooler
    {
        public int id { get; set; }
        public int socketid { get; set; }
        public int processorcoolerid { get; set; }
    
        public virtual processorcooler processorcooler { get; set; }
        public virtual socket socket { get; set; }
    }
}
