//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR15
{
    using System;
    using System.Collections.Generic;
    
    public partial class storagedevice
    {
        public int id { get; set; }
        public int capacity { get; set; }
        public int storagedeviceinterfaceid { get; set; }
        public int storagedevicetypeid { get; set; }
    
        public virtual basepart basepart { get; set; }
        public virtual hdd hdd { get; set; }
        public virtual ssd ssd { get; set; }
        public virtual storagedeviceinterface storagedeviceinterface { get; set; }
        public virtual storagedevicetype storagedevicetype { get; set; }
    }
}
