//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP523_Arkhipova
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PR8_shopEntities : DbContext
    {
        public PR8_shopEntities()
            : base("name=PR8_shopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<korzina> korzina { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_korzina> product_korzina { get; set; }
        public virtual DbSet<pvz> pvz { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<zakaz> zakaz { get; set; }
        public virtual DbSet<zakaz_product> zakaz_product { get; set; }
    }
}
