//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP523_Arkhipova
{
    using System;
    using System.Collections.Generic;
    
    public partial class process
    {
        public int ID_process { get; set; }
        public int ID_client { get; set; }
        public int ID_player { get; set; }
        public string status { get; set; }
        public double price { get; set; }
        public int nuzna_detal { get; set; }
        public Nullable<int> postavilli_detal { get; set; }
    
        public virtual client client { get; set; }
        public virtual detal detal { get; set; }
        public virtual detal detal1 { get; set; }
        public virtual player player { get; set; }
    }
}
