//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP523_Arkhipova
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_korzina
    {
        public int ID_product_korzina { get; set; }
        public int ID_product { get; set; }
        public int ID_korzina { get; set; }
    
        public virtual korzina korzina { get; set; }
        public virtual product product { get; set; }
    }
}
