//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP523_Arkhipova
{
    using System;
    using System.Collections.Generic;
    
    public partial class sklad
    {
        public int ID_sklad { get; set; }
        public int ID_zakaz { get; set; }
        public int ID_player { get; set; }
        public int kol_vo { get; set; }
    
        public virtual player player { get; set; }
        public virtual zakaz zakaz { get; set; }
    }
}
