//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP523_Arkhipova
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz_product
    {
        public int ID_zakaz_product { get; set; }
        public int ID_zakaz { get; set; }
        public int ID_product { get; set; }
        public double price { get; set; }
        public int kol_vo { get; set; }
    
        public virtual product product { get; set; }
        public virtual zakaz zakaz { get; set; }
    }
}
