//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR14
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmGenre
    {
        public string FilmGenreID { get; set; }
        public int FilmID { get; set; }
        public int GenreID { get; set; }
    
        public virtual Films Films { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
