//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR14
{
    using System;
    using System.Collections.Generic;
    
    public partial class SitSession
    {
        public int SitSessionID { get; set; }
        public int SessionID { get; set; }
        public int SitID { get; set; }
        public bool IsTake { get; set; }
    
        public virtual Session Session { get; set; }
        public virtual Sit Sit { get; set; }
    }
}
