//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorRoleRequests
    {
        public int ID_Request { get; set; }
        public int ID_Users { get; set; }
        public int ID_RequestStatuses { get; set; }
    
        public virtual RequestStatuses RequestStatuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
