//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int ID_Compl { get; set; }
        public int ID_Users { get; set; }
        public Nullable<int> ID_Book { get; set; }
        public Nullable<int> ID_Reviews { get; set; }
        public string text { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reviews Reviews { get; set; }
        public virtual Users Users { get; set; }
    }
}
