//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingLists
    {
        public int ID_Lists { get; set; }
        public int ID_Users { get; set; }
        public int ID_Book { get; set; }
        public int ID_StatB { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual StatusBook StatusBook { get; set; }
        public virtual Users Users { get; set; }
    }
}
